### ISSUE TITLE
Filter to show all sprectrograms tagged "Unsure"

### ISSUE THREAD

**Issue by nellihol** [ecoacoustics/web-components#192] opened 2024-09-19 01:17 UTC
Stakeholders P and N wanted a page listing all spectrograms tagged unsure.

Additionally, stakeholder N mentioned that they want to be able to send this page to someone else to verify the ones they are unsure about.

**Comment by atruskie** [comment] 2024-09-19 02:46
Duplicate of #138

**Closed by atruskie** 2024-09-19 02:46 UTC
Labels: discussion needed, stakeholder-N, stakeholder-P
