### ISSUE TITLE
Automatic tile advancement

### ISSUE THREAD

**Issue by nellihol** [ecoacoustics/web-components#188] opened 2024-09-19 00:49 UTC
Stakeholder D was hoping to see the first tile automatically selected and the selection moved to the next tile automatically once a verification decision was made.  Always selecting the first tile by default would clash with the "select all if nothing is selected" feature. Maybe this could be a setting? #179 

## Describe alternatives you've considered
If the user selects one tile and does a decision, the selection moves to the next tile automatically.

**Comment by atruskie** [comment] 2024-09-19 02:41
Duplicate of #136

**Closed by atruskie** 2024-09-19 02:41 UTC
Labels: discussion needed, stakeholder-P, stakeholder-D, ui
